### PR TITLE
61 oauth token [WIP]

### PR DESCRIPTION
**Pull request by JeanJoeris**
This adds api endpoint for getting an oauth token. It does not current add any requirements for this oauth token into other api calls

### CODE REVIEW

**Comment by JeanJoeris** [comment]
@jmejia - Would love code review on this as well. Is the idea of having a table storing users, their authorized app and the associated code/token the right path?

**Comment by JeanJoeris** [comment]
I've mostly been working off of https://www.digitalocean.com/community/tutorials/an-introduction-to-oauth-2 and building it with a grant type of authorization_code

**Comment by JeanJoeris** [comment]
Should finally be ready for code review @brendandillon @susiirwin @rdavid1099

**Comment by rvna** [comment]
This looks really nice. I like the new format for the index return, and functioning oauth is super impressive.

**Pull request merged**
